### ISSUE TITLE
404s on other pages and broken component on homepage

### ISSUE THREAD

**Issue by maxeonyx** [emmettgb/EmsComputer.jl#1]
I went to your website to see if you had another version of this article available (I reached my "free article" limit): https://towardsdatascience.com/the-depressing-challenges-facing-the-julia-programming-language-in-2021-34c748968ab7

But, I guess your website is underdevelopment. When I click on your about, content and projects pages I get a 404.

Also, on the homepage there is a broken component:
![image](https://user-images.githubusercontent.com/5790555/166406189-b554eaf1-35b1-4d81-a015-f6f5b8a083d3.png)

**Comment by emmaccode** [comment]
Still a work in progress ! I am building the web-development framework as I am building the website. Once there is a solid release, I will be going through and designing a scalable version -- the main purpose in all honesty was to try and deploy something with SSL, testing environments and routing and such.
Still more to do as well.
Also, just open the medium page in incognito mode.

**Comment by emmaccode** [comment]
I shall now close this, as EmsComputer has taken a dramatic shaping !
